version: '3.1'

services:
  my-first-rekit-project:
    container_name: my-first-rekit-project
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - './src:/app'
      - 'node_modules:/app/node_modules'
    ports:
      - 8030:8030
    environment:
      - CHOKIDAR_USEPOLLING=true

  rekit-studio:
    container_name: rekit-studio
    build:
      context: ./src
      dockerfile: rekit.Dockerfile
    volumes:
      - './src:/app'
      - 'node_modules:/app/node_modules'
    ports:
      - 8031:8031
    environment:
      - CHOKIDAR_USEPOLLING=true  

volumes:
  node_modules: