version: '3.1'

services:
  my-first-rekit-project:
    container_name: my-first-rekit-project
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - './src:/app'
      - '/app/node_modules'
    ports:
      - 8030:3100
      - 35729:35729
    environment:
      - CHOKIDAR_USEPOLLING=true

  rekit-studio:
    container_name: rekit-studio
    build:
      context: ./src
      dockerfile: rekit.Dockerfile
    volumes:
      - './src:/app'
      - '/app/node_modules'
    ports:
      - 8031:3040
    environment:
      - CHOKIDAR_USEPOLLING=true  